import { NextResponse } from "next/server"

export async function GET() {
  const cities = [
  "Agarathenna",
  "Ahangama",
  "Ahungalla",
  "Akkaraipattu",
  "Akurana",
  "Alawathugoda",
  "Aluthgama",
  "Aluthkade",
  "Aluthkade East",
  "Aluthmawatha",
  "Aluvihare",
  "Ambalangoda",
  "Ambepussa",
  "Amithirigala",
  "Ampara",
  "Amunakole",
  "Anamaduwa",
  "Andigama",
  "Anuradhapura",
  "Aranayaka",
  "Arangala Junction",
  "Arugam Bay",
  "Asgiriya",
  "Athurugiriya",
  "Avissawella",
  "Awariwatte",
  "Badulla",
  "Baduluwela",
  "Bakinigahawela",
  "Balagolla",
  "Balangoda",
  "Bambalapitiya",
  "Bambarapana",
  "Bangadeniya",
  "Bandaragama",
  "Bandarawela",
  "Batticaloa",
  "Batuwatta",
  "Belihuloya",
  "Belummahara",
  "Bentota",
  "Beruwala",
  "Bloemendhal",
  "Boliyadda",
  "Bopitiya",
  "Boralesgamuwa",
  "Borella",
  "Boralankada",
  "Buduruwagala",
  "Bulanawewa",
  "Chavakachcheri",
  "Chempian Pattu South",
  "Chilaw",
  "Chunnavil",
  "Cinnamon Garden",
  "Colombo",
  "Dadalla",
  "Dahamgama",
  "Dalugama",
  "Dambadeniya",
  "Dambulla",
  "Debarawewa",
  "Dehiwala",
  "Dehiwala-Mount Lavinia",
  "Dematagoda",
  "Demodara",
  "Dikwella",
  "Dimbulagala",
  "Dodanduwa",
  "Egal Oya",
  "Ella",
  "Elakanda",
  "Embekka",
  "Embilipitiya",
  "Eravur",
  "Fort",
  "Gadaladeniya",
  "Galle",
  "Galkadawala",
  "Galoya",
  "Gampaha",
  "Gampola",
  "Ganewalpola",
  "Giragama",
  "Girithale",
  "Godunna",
  "Gonagaldeniya",
  "Grandpass",
  "Gurugalla",
  "Habaraduwa",
  "Habarana",
  "Hadungama",
  "Hambantota",
  "Hanwella",
  "Haputale",
  "Harasbedda",
  "Hatton-Dickoya",
  "Havelock Town",
  "High Forest",
  "Hikkaduwa",
  "Hingurakgoda",
  "Hokandara",
  "Homagama",
  "Hopton",
  "Horana",
  "Hulftsdorp",
  "Hunnasgiriya",
  "Idalgashinna",
  "Ihalagama",
  "Induruwa",
  "Ja-Ela",
  "Jaffna",
  "Kadawatha",
  "Kadugannawa",
  "Kaduwela",
  "Kahathuduwa",
  "Kalaoya",
  "Kalkudah",
  "Kalmunai",
  "Kalpitiya",
  "Kalubowila",
  "Kalutara",
  "Kandalama",
  "Kandana",
  "Kandy",
  "Kanthasamy Nagar",
  "Kapugollewa",
  "Karapitiya",
  "Katharagama",
  "Katiyawa Yaya 04",
  "Kattankudy",
  "Katunayake",
  "Katunayake-Seeduwa",
  "Kebutigollewa",
  "Kegalle",
  "Kelaniya",
  "Kesbewa",
  "Kilinochchi",
  "Kinniya",
  "Kirinda",
  "Kirilapone North",
  "Kirulapana",
  "Kitulgala",
  "Kohuwala",
  "Kokupadaiyan",
  "Koggala",
  "Kollupitiya",
  "Kolonnawa",
  "Kosgoda",
  "Koswatte",
  "Kotahena",
  "Kotikawatta",
  "Kottagala",
  "Kottawa",
  "Kothmale",
  "Koyyawadi",
  "Kudawa",
  "Kuliyapitiya",
  "Kurunegala",
  "Lukasgoda",
  "Madampitiya",
  "Madulla",
  "Madurankuliya",
  "Mahagama",
  "Mahagirilla",
  "Maha Uva",
  "Maharagama",
  "Mahiyangana",
  "Malabe",
  "Maligawatta",
  "Mallakam",
  "Mandaramnuwara",
  "Mannar",
  "Maragahawewa",
  "Maradana",
  "Mari Arawa",
  "Matale",
  "Matara",
  "Mattakkuliya",
  "Mawanella",
  "Mayiliddithurai",
  "Meetiyagoda",
  "Meemure",
  "Metigahathenna",
  "Mihintale",
  "Minneriya",
  "Mirissa",
  "Modara",
  "Moneragala",
  "Moratuwa",
  "Mount-Lavinia",
  "Mullaitivu",
  "Mulleriyawa",
  "Nanuoya",
  "Narahenpita",
  "Nawalapitiya",
  "Nawala",
  "Nawadankulama",
  "Negombo",
  "Nilaveli",
  "Nildandahinna",
  "Nugegoda",
  "Nuwara Eliya",
  "Ohiya",
  "Pahala Maragahawewa",
  "Pallewela",
  "Pamankada",
  "Panadura",
  "Panchikawatta",
  "Pannipitiya",
  "Pasikudah",
  "Passara",
  "Pelawatte",
  "Peliyagoda",
  "Pettah",
  "Pilimathalawa",
  "Piliyandala",
  "Pinnawala",
  "Point Pedro",
  "Polonnaruwa",
  "Polygandy",
  "Ponnalai",
  "Poonugala",
  "Pottuvil",
  "Poyiddy",
  "Puliyankulam",
  "Pundaluoya",
  "Puttalam",
  "Puwakgahaulpotha",
  "Ragama",
  "Rajagiriya",
  "Raja Ela",
  "Ralapanawa",
  "Ramboda",
  "Ranna",
  "Ratmalana",
  "Ratnapura",
  "Rathgama",
  "Ruwanwella",
  "Sainthamarathu",
  "Sea Fourth",
  "Seeduwa",
  "Sigiriya",
  "Sinharagama",
  "Sinnadampan",
  "Slave Island",
  "Sri Jayawardenepura Kotte",
  "Talalla",
  "Talpe",
  "Tangalle",
  "Thamannawetiya",
  "Thambana",
  "Thandiyadi",
  "Tissamaharama",
  "Trincomalee",
  "Udayarkaddu",
  "Udawalawa",
  "Udawalawe National Park",
  "Udapanguwagama",
  "Ulkatupotha",
  "Unawatuna",
  "Uppuveli",
  "Urumeewala",
  "Vakarai",
  "Valvettithurai",
  "Vavuniya",
  "Veravil",
  "Viyaluwa",
  "Wadduwa",
  "Walaliya",
  "Wariyapola",
  "Watagoda",
  "Wattala",
  "Wattegama",
  "Wedinagala EP",
  "Welikada",
  "Weligama",
  "Weligatta",
  "Wellawatte",
  "Westhall",
  "Wickramasinghapura",
  "Yakkurugala",
  "Yala National Park",
  "Yatiyanthota",
  "Yoda Kandiya"
  ]

  return NextResponse.json({ cities })
}
